version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
  
volumes:
  mongodb_data_container: 